# Copyright 2017 Vector Creations Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3'
services:
    nginx:
        image: nginx:1.12
        networks:
            - frontend
            - backend
        ports:
            - "9090:80"
        volumes:
            - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ../jitsi-meet:/usr/share/nginx/html:ro
            - ./config/config.js:/usr/share/nginx/html/config.js:ro
        restart: unless-stopped
    prosody:
        image: prosody/prosody:0.9.12
        environment:
            LOCAL: focus
            DOMAIN: auth.jitsi.sinbadflyce.com
            PASSWORD: Test1009
        networks:
            - backend
        expose:
            - "5280" # nginx
            - "5222" # jicofo
        ports:
            - "5347:5347" # jicofo, videobridge; bound to host as videobridge uses network_mode: host
        volumes:
            - ./config/mod_turncredentials.lua:/usr/lib/prosody/modules/mod_turncredentials/mod_turncredentials.lua
            - ./config/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua
            - prosody-logs:/var/log/prosody
        restart: unless-stopped
    jicofo:
        build: ./jicofo
        environment:
            XMPP_HOST: jitsi.sinbadflyce.com
            XMPP_DOMAIN: jitsi.sinbadflyce.com
            JICOFO_XMPP_FOCUS_SECRET: Test1009
            JICOFO_XMPP_FOCUS_USER_PASSWORD: Test1009
        networks:
            - backend
        restart: unless-stopped
    videobridge:
        build: ./videobridge
        environment:
            XMPP_HOST: 127.0.0.1 # using network_mode: host so prosody is reachable at 127.0.0.1:5347
            XMPP_DOMAIN: jitsi.sinbadflyce.com
            VIDEOBRIDGE_XMPP_SECRET: Test1009
        network_mode: host
        restart: unless-stopped
volumes:
    prosody-logs:
networks:
    frontend:
    backend:
